//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nsync.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nsync.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient access rights to the folders..
        /// </summary>
        public static string accessRightsInsufficient {
            get {
                return ResourceManager.GetString("accessRightsInsufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both the selected folders do not exist..
        /// </summary>
        public static string bothFoldersNotExist {
            get {
                return ResourceManager.GetString("bothFoldersNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Exclude List.
        /// </summary>
        public static string clearToolTip {
            get {
                return ResourceManager.GetString("clearToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string closeToolTip {
            get {
                return ResourceManager.GetString("closeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd.
        /// </summary>
        public static string dateFormat {
            get {
                return ResourceManager.GetString("dateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nsync\debug\.
        /// </summary>
        public static string debugFolderPath {
            get {
                return ResourceManager.GetString("debugFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END OF DEBUG LOG.
        /// </summary>
        public static string debugLoggerClosingMessage {
            get {
                return ResourceManager.GetString("debugLoggerClosingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again..
        /// </summary>
        public static string defaultErrorMessage {
            get {
                return ResourceManager.GetString("defaultErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag &amp; drop files and folders to exclude..
        /// </summary>
        public static string excludeDragDropMessage {
            get {
                return ResourceManager.GetString("excludeDragDropMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude All Files: .
        /// </summary>
        public static string excludeFilesDescription {
            get {
                return ResourceManager.GetString("excludeFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude File Type: .
        /// </summary>
        public static string excludeFileTypesDescription {
            get {
                return ResourceManager.GetString("excludeFileTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Folder: .
        /// </summary>
        public static string excludeFolderDescription {
            get {
                return ResourceManager.GetString("excludeFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag &amp; Drop Files or Folders to Exclude.
        /// </summary>
        public static string excludeIconToolTip {
            get {
                return ResourceManager.GetString("excludeIconToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not in synchronized folders: .
        /// </summary>
        public static string excludeInvalidDescription {
            get {
                return ResourceManager.GetString("excludeInvalidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Folder Included: .
        /// </summary>
        public static string excludeParentIncludedDescription {
            get {
                return ResourceManager.GetString("excludeParentIncludedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on entries to remove them from the exclude list..
        /// </summary>
        public static string excludeRemoveMessage {
            get {
                return ResourceManager.GetString("excludeRemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Exclude Root Folder: .
        /// </summary>
        public static string excludeRootFolder {
            get {
                return ResourceManager.GetString("excludeRootFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag &amp; Drop Files or Folders to Exclude.
        /// </summary>
        public static string excludeText {
            get {
                return ResourceManager.GetString("excludeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified argument was out of the range of valid values..
        /// </summary>
        public static string excludingFileTypesException {
            get {
                return ResourceManager.GetString("excludingFileTypesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s) Open. Please Close File(s) And Try Again.
        /// </summary>
        public static string fileNotAccessible {
            get {
                return ResourceManager.GetString("fileNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process cannot access the file because it is being used by another process.
        /// </summary>
        public static string filesOpenedExceptionMessage {
            get {
                return ResourceManager.GetString("filesOpenedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to synchronise with nsync..
        /// </summary>
        public static string folderExplorerText {
            get {
                return ResourceManager.GetString("folderExplorerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://siteoforigin:,,,/Resources/Icons/folder.png.
        /// </summary>
        public static string folderIconPath {
            get {
                return ResourceManager.GetString("folderIconPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nsync is having problems accessing the folder. Please close any applications that are using this folder or free up more disk space..
        /// </summary>
        public static string folderIOException {
            get {
                return ResourceManager.GetString("folderIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://siteoforigin:,,,/Resources/Icons/folder_missing.png.
        /// </summary>
        public static string folderMissingIconPath {
            get {
                return ResourceManager.GetString("folderMissingIconPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder has file(s)/folder(s) that do not exist..
        /// </summary>
        public static string folderNotExists {
            get {
                return ResourceManager.GetString("folderNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your last synced folder pair on this removeable disk is restored..
        /// </summary>
        public static string folderOnRemovableDiskRestored {
            get {
                return ResourceManager.GetString("folderOnRemovableDiskRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder has file(s)/folder(s) with path names exceeding the limit..
        /// </summary>
        public static string folderPathTooLong {
            get {
                return ResourceManager.GetString("folderPathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder has file(s)/folder(s) with restricted file security permissions. Please close any applications that are using this folder..
        /// </summary>
        public static string folderRestrictedAccess {
            get {
                return ResourceManager.GetString("folderRestrictedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid table or properties.
        /// </summary>
        public static string getSystemInfoErrorMessage {
            get {
                return ResourceManager.GetString("getSystemInfoErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string homeToolTip {
            get {
                return ResourceManager.GetString("homeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient disk space.
        /// </summary>
        public static string insufficientDiskSpace {
            get {
                return ResourceManager.GetString("insufficientDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left folder has insufficient disk space..
        /// </summary>
        public static string leftFolderInsufficientDiskSpace {
            get {
                return ResourceManager.GetString("leftFolderInsufficientDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nsync is having problems accessing the left folder. Please close any applications that are using this folder or free up more disk space..
        /// </summary>
        public static string leftFolderIOException {
            get {
                return ResourceManager.GetString("leftFolderIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /nsync/MRU/left1.
        /// </summary>
        public static string leftFolderMRUPath {
            get {
                return ResourceManager.GetString("leftFolderMRUPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The left folder does not exist..
        /// </summary>
        public static string leftFolderNotExist {
            get {
                return ResourceManager.GetString("leftFolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The left folder has file(s)/folder(s) that do not exist..
        /// </summary>
        public static string leftFolderNotExistsForTrackBack {
            get {
                return ResourceManager.GetString("leftFolderNotExistsForTrackBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The left folder has file(s)/folder(s) with path names exceeding the limit..
        /// </summary>
        public static string leftFolderPathTooLong {
            get {
                return ResourceManager.GetString("leftFolderPathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The left folder has file(s)/folder(s) with restricted file security permissions..
        /// </summary>
        public static string leftFolderRestrictedAccess {
            get {
                return ResourceManager.GetString("leftFolderRestrictedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nsync\log\.
        /// </summary>
        public static string logFolderPath {
            get {
                return ResourceManager.GetString("logFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied. .
        /// </summary>
        public static string messageAccessDeniedError {
            get {
                return ResourceManager.GetString("messageAccessDeniedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up folders....
        /// </summary>
        public static string messageBackingUpFolders {
            get {
                return ResourceManager.GetString("messageBackingUpFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error detected.
        /// </summary>
        public static string messageErrorDetected {
            get {
                return ResourceManager.GetString("messageErrorDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Folder is Locked.\n Path : .
        /// </summary>
        public static string messageLogFolderLocked {
            get {
                return ResourceManager.GetString("messageLogFolderLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No listview visible!.
        /// </summary>
        public static string messageNoListView {
            get {
                return ResourceManager.GetString("messageNoListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nsync Folder is Locked.\n Path : .
        /// </summary>
        public static string messageNsyncFolderLocked {
            get {
                return ResourceManager.GetString("messageNsyncFolderLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing folders....
        /// </summary>
        public static string messagePreparingFolders {
            get {
                return ResourceManager.GetString("messagePreparingFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore completed.
        /// </summary>
        public static string messageRestoreCompleted {
            get {
                return ResourceManager.GetString("messageRestoreCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring folders....
        /// </summary>
        public static string messageRestoringFolders {
            get {
                return ResourceManager.GetString("messageRestoringFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings File is Locked.\n Path : .
        /// </summary>
        public static string messageSettingsXmlLocked {
            get {
                return ResourceManager.GetString("messageSettingsXmlLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync completed.
        /// </summary>
        public static string messageSyncCompleted {
            get {
                return ResourceManager.GetString("messageSyncCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing folders....
        /// </summary>
        public static string messageSyncingFolders {
            get {
                return ResourceManager.GetString("messageSyncingFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync terminated.
        /// </summary>
        public static string messageSyncTerminated {
            get {
                return ResourceManager.GetString("messageSyncTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .metadata.
        /// </summary>
        public static string metaDataFileExtension {
            get {
                return ResourceManager.GetString("metaDataFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filesync.metadata.
        /// </summary>
        public static string metadataFileName {
            get {
                return ResourceManager.GetString("metadataFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimise.
        /// </summary>
        public static string minimiseToolTip {
            get {
                return ResourceManager.GetString("minimiseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nsync has modified the left folder path to help you sync to the correct place..
        /// </summary>
        public static string modifiedLeftPath {
            get {
                return ResourceManager.GetString("modifiedLeftPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nsync has modified the right folder path to help you sync to the correct place..
        /// </summary>
        public static string modifiedRightPath {
            get {
                return ResourceManager.GetString("modifiedRightPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string nextToolTip {
            get {
                return ResourceManager.GetString("nextToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n/a.
        /// </summary>
        public static string notApplicable {
            get {
                return ResourceManager.GetString("notApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nsync\.
        /// </summary>
        public static string nsyncFolderPath {
            get {
                return ResourceManager.GetString("nsyncFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nsync.xml.
        /// </summary>
        public static string nsyncXMLFilename {
            get {
                return ResourceManager.GetString("nsyncXMLFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string nullString {
            get {
                return ResourceManager.GetString("nullString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag or Click to Add a Folder.
        /// </summary>
        public static string panelIconToolTip {
            get {
                return ResourceManager.GetString("panelIconToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag &amp; Drop Folders Here.
        /// </summary>
        public static string panelText {
            get {
                return ResourceManager.GetString("panelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Preview.
        /// </summary>
        public static string previewButtonToolTip {
            get {
                return ResourceManager.GetString("previewButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore done!.
        /// </summary>
        public static string restoreComplete {
            get {
                return ResourceManager.GetString("restoreComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore folder.
        /// </summary>
        public static string restoreToolTip {
            get {
                return ResourceManager.GetString("restoreToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right folder has insufficient disk space..
        /// </summary>
        public static string rightFolderInsufficientDiskSpace {
            get {
                return ResourceManager.GetString("rightFolderInsufficientDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nsync is having problems accessing the right folder. Please close any applications that are using this folder or free up more disk space..
        /// </summary>
        public static string rightFolderIOException {
            get {
                return ResourceManager.GetString("rightFolderIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /nsync/MRU/right1.
        /// </summary>
        public static string rightFolderMRUPath {
            get {
                return ResourceManager.GetString("rightFolderMRUPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The right folder does not exist..
        /// </summary>
        public static string rightFolderNotExist {
            get {
                return ResourceManager.GetString("rightFolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The right folder has file(s)/folder(s) that do not exist..
        /// </summary>
        public static string rightFolderNotExistsForTrackBack {
            get {
                return ResourceManager.GetString("rightFolderNotExistsForTrackBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The right folder has file(s)/folder(s) with path names exceeding the limit..
        /// </summary>
        public static string rightFolderPathTooLong {
            get {
                return ResourceManager.GetString("rightFolderPathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The right folder has file(s)/folder(s) with restricted file security permissions..
        /// </summary>
        public static string rightFolderRestrictedAccess {
            get {
                return ResourceManager.GetString("rightFolderRestrictedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nsync\settings.xml.
        /// </summary>
        public static string settingsFilePath {
            get {
                return ResourceManager.GetString("settingsFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settingsToolTip {
            get {
                return ResourceManager.GetString("settingsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.xml.
        /// </summary>
        public static string settingsXMLFilename {
            get {
                return ResourceManager.GetString("settingsXMLFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The left and right folders cannot be similar..
        /// </summary>
        public static string similarFolders {
            get {
                return ResourceManager.GetString("similarFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Sync.
        /// </summary>
        public static string stopButtonToolTip {
            get {
                return ResourceManager.GetString("stopButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders that are to be synchronized cannot be a subfolder of each other..
        /// </summary>
        public static string subfolderOfFolder {
            get {
                return ResourceManager.GetString("subfolderOfFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And Sync!.
        /// </summary>
        public static string syncButtonToolTip {
            get {
                return ResourceManager.GetString("syncButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync done!.
        /// </summary>
        public static string syncComplete {
            get {
                return ResourceManager.GetString("syncComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders are already synchronized..
        /// </summary>
        public static string synchronizedFolders {
            get {
                return ResourceManager.GetString("synchronizedFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync terminated!.
        /// </summary>
        public static string syncTerminated {
            get {
                return ResourceManager.GetString("syncTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://siteoforigin:,,,/Resources/Icons/removabledrive.png.
        /// </summary>
        public static string thumbdriveIconPath {
            get {
                return ResourceManager.GetString("thumbdriveIconPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hh.mm.ss tt.
        /// </summary>
        public static string timeFormat {
            get {
                return ResourceManager.GetString("timeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd hh.mm.ss tt.
        /// </summary>
        public static string timeStampFormat {
            get {
                return ResourceManager.GetString("timeStampFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _nsync_trackback.
        /// </summary>
        public static string trackBackFolderName {
            get {
                return ResourceManager.GetString("trackBackFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _trackback.xml.
        /// </summary>
        public static string trackBackMetaDataFileName {
            get {
                return ResourceManager.GetString("trackBackMetaDataFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /nsync/TrackBack.
        /// </summary>
        public static string trackBackPath {
            get {
                return ResourceManager.GetString("trackBackPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /nsync/TrackBack/session.
        /// </summary>
        public static string trackBackSessionPath {
            get {
                return ResourceManager.GetString("trackBackSessionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrackBack.
        /// </summary>
        public static string trackBackToolTip {
            get {
                return ResourceManager.GetString("trackBackToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _trackback.xml.
        /// </summary>
        public static string trackbackXMLFilename {
            get {
                return ResourceManager.GetString("trackbackXMLFilename", resourceCulture);
            }
        }
    }
}
