#pragma checksum "..\..\SettingsPage.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "B9DD8A556FAB1936DB98989D2FAEF2E7"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;


namespace nsync {
    
    
    /// <summary>
    /// SettingsPage
    /// </summary>
    public partial class SettingsPage : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector {
        
        
        #line 7 "..\..\SettingsPage.xaml"
        internal System.Windows.Controls.Image ImageSettings;
        
        #line default
        #line hidden
        
        
        #line 8 "..\..\SettingsPage.xaml"
        internal System.Windows.Controls.StackPanel PanelSettings;
        
        #line default
        #line hidden
        
        
        #line 10 "..\..\SettingsPage.xaml"
        internal System.Windows.Controls.Label HelperWindowSettingsDescription;
        
        #line default
        #line hidden
        
        
        #line 11 "..\..\SettingsPage.xaml"
        internal System.Windows.Controls.Slider HelperWindowSlider;
        
        #line default
        #line hidden
        
        
        #line 12 "..\..\SettingsPage.xaml"
        internal System.Windows.Controls.ComboBox HelperWindowSliderValue;
        
        #line default
        #line hidden
        
        
        #line 13 "..\..\SettingsPage.xaml"
        internal System.Windows.Controls.ComboBoxItem SliderValue0;
        
        #line default
        #line hidden
        
        
        #line 14 "..\..\SettingsPage.xaml"
        internal System.Windows.Controls.ComboBoxItem SliderValue1;
        
        #line default
        #line hidden
        
        
        #line 15 "..\..\SettingsPage.xaml"
        internal System.Windows.Controls.ComboBoxItem SliderValue2;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\SettingsPage.xaml"
        internal System.Windows.Controls.ComboBoxItem SliderValue3;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\SettingsPage.xaml"
        internal System.Windows.Controls.ComboBoxItem SliderValue4;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\SettingsPage.xaml"
        internal System.Windows.Controls.ComboBoxItem SliderValue5;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\SettingsPage.xaml"
        internal System.Windows.Controls.ComboBoxItem SliderValue6;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\SettingsPage.xaml"
        internal System.Windows.Controls.ComboBoxItem SliderValue7;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\SettingsPage.xaml"
        internal System.Windows.Controls.ComboBoxItem SliderValue8;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\SettingsPage.xaml"
        internal System.Windows.Controls.ComboBoxItem SliderValue9;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\SettingsPage.xaml"
        internal System.Windows.Controls.ComboBoxItem SliderValue10;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\SettingsPage.xaml"
        internal System.Windows.Controls.ComboBoxItem SliderValueMax;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\SettingsPage.xaml"
        internal System.Windows.Controls.CheckBox CheckboxToggleExcludeWindow;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\SettingsPage.xaml"
        internal System.Windows.Controls.CheckBox CheckboxToggleTrackBack;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\SettingsPage.xaml"
        internal System.Windows.Controls.Button ButtonOpenLogFolder;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\SettingsPage.xaml"
        internal System.Windows.Controls.Button ButtonClearLogFolder;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\SettingsPage.xaml"
        internal System.Windows.Controls.Button ButtonClearMetaData;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\SettingsPage.xaml"
        internal System.Windows.Controls.Button ButtonClearSettings;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\SettingsPage.xaml"
        internal System.Windows.Controls.Label LabelProgress;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/nsync;component/settingspage.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\SettingsPage.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.ImageSettings = ((System.Windows.Controls.Image)(target));
            return;
            case 2:
            this.PanelSettings = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 3:
            this.HelperWindowSettingsDescription = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.HelperWindowSlider = ((System.Windows.Controls.Slider)(target));
            
            #line 11 "..\..\SettingsPage.xaml"
            this.HelperWindowSlider.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.HelperWindowSlider_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 5:
            this.HelperWindowSliderValue = ((System.Windows.Controls.ComboBox)(target));
            
            #line 12 "..\..\SettingsPage.xaml"
            this.HelperWindowSliderValue.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.HelperWindowSliderValue_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 6:
            this.SliderValue0 = ((System.Windows.Controls.ComboBoxItem)(target));
            return;
            case 7:
            this.SliderValue1 = ((System.Windows.Controls.ComboBoxItem)(target));
            return;
            case 8:
            this.SliderValue2 = ((System.Windows.Controls.ComboBoxItem)(target));
            return;
            case 9:
            this.SliderValue3 = ((System.Windows.Controls.ComboBoxItem)(target));
            return;
            case 10:
            this.SliderValue4 = ((System.Windows.Controls.ComboBoxItem)(target));
            return;
            case 11:
            this.SliderValue5 = ((System.Windows.Controls.ComboBoxItem)(target));
            return;
            case 12:
            this.SliderValue6 = ((System.Windows.Controls.ComboBoxItem)(target));
            return;
            case 13:
            this.SliderValue7 = ((System.Windows.Controls.ComboBoxItem)(target));
            return;
            case 14:
            this.SliderValue8 = ((System.Windows.Controls.ComboBoxItem)(target));
            return;
            case 15:
            this.SliderValue9 = ((System.Windows.Controls.ComboBoxItem)(target));
            return;
            case 16:
            this.SliderValue10 = ((System.Windows.Controls.ComboBoxItem)(target));
            return;
            case 17:
            this.SliderValueMax = ((System.Windows.Controls.ComboBoxItem)(target));
            return;
            case 18:
            this.CheckboxToggleExcludeWindow = ((System.Windows.Controls.CheckBox)(target));
            
            #line 29 "..\..\SettingsPage.xaml"
            this.CheckboxToggleExcludeWindow.Checked += new System.Windows.RoutedEventHandler(this.CheckboxToggleExcludeWindow_Checked);
            
            #line default
            #line hidden
            
            #line 29 "..\..\SettingsPage.xaml"
            this.CheckboxToggleExcludeWindow.Unchecked += new System.Windows.RoutedEventHandler(this.CheckboxToggleExcludeWindow_UnChecked);
            
            #line default
            #line hidden
            return;
            case 19:
            this.CheckboxToggleTrackBack = ((System.Windows.Controls.CheckBox)(target));
            
            #line 32 "..\..\SettingsPage.xaml"
            this.CheckboxToggleTrackBack.Checked += new System.Windows.RoutedEventHandler(this.CheckboxToggleTrackBack_Checked);
            
            #line default
            #line hidden
            
            #line 32 "..\..\SettingsPage.xaml"
            this.CheckboxToggleTrackBack.Unchecked += new System.Windows.RoutedEventHandler(this.CheckboxToggleTrackBack_UnChecked);
            
            #line default
            #line hidden
            return;
            case 20:
            this.ButtonOpenLogFolder = ((System.Windows.Controls.Button)(target));
            
            #line 35 "..\..\SettingsPage.xaml"
            this.ButtonOpenLogFolder.Click += new System.Windows.RoutedEventHandler(this.ButtonOpenLogFolder_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.ButtonClearLogFolder = ((System.Windows.Controls.Button)(target));
            
            #line 36 "..\..\SettingsPage.xaml"
            this.ButtonClearLogFolder.Click += new System.Windows.RoutedEventHandler(this.ButtonClearLogFolder_Click);
            
            #line default
            #line hidden
            return;
            case 22:
            this.ButtonClearMetaData = ((System.Windows.Controls.Button)(target));
            
            #line 39 "..\..\SettingsPage.xaml"
            this.ButtonClearMetaData.Click += new System.Windows.RoutedEventHandler(this.ButtonClearMetaData_Click);
            
            #line default
            #line hidden
            return;
            case 23:
            this.ButtonClearSettings = ((System.Windows.Controls.Button)(target));
            
            #line 40 "..\..\SettingsPage.xaml"
            this.ButtonClearSettings.Click += new System.Windows.RoutedEventHandler(this.ButtonClearSettings_Click);
            
            #line default
            #line hidden
            return;
            case 24:
            this.LabelProgress = ((System.Windows.Controls.Label)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}
